### ISSUE TITLE
How do you change the header_name

### ISSUE THREAD

**Issue by syahdeini** [cwaldbieser/jhub_remote_user_authenticator#15]
It looks like you need to create a new class to do this. Is there any easy way?

**Comment by cwaldbieser** [comment]
In `RemoteUserLocalAuthenticator`, The class attribute `header_name` is a `Unicode` traitlet.  I forget the exact syntax, but you should be able to set this as a property in your JupyterHub config file.  It is similar to how other settings in JupyterHub are defined.

**Comment by cwaldbieser** [comment]
Take a look at this [repo](https://github.com/cwaldbieser/vagrant_jhub_remote_user_authenticator_test_env/blob/master/srv/jupyterhub/jupyterhub_config.py) I use for running tests.  The line:

    c.RemoteUserLocalAuthenticator.header_name = 'X-Remote-User'

is what you want, I think.
