### ISSUE TITLE
use with other authenticator_class

### ISSUE THREAD

**Issue by keith6014** [cwaldbieser/jhub_remote_user_authenticator#23]
I can get the remote_user with nginx, no problem. 
I would like to then authenticate with LDAP (ldapauthenticator.LDAPAuthenticator). Is that possible?

**Comment by keith6014** [comment]
any ideas?

**Comment by cwaldbieser** [comment]
The Remote User authenticator really just assumes that authentication has already happened outside of JupyterHub and that the REMOTE_USER header can be trusted.  So I'm not exactly sure what you're trying to accomplish.  If you authenticate with LDAP initially, you'll have LDAP authentication and you wouldn't need REMOTE_USER.

If you have a particular use case for the scenario you proposed, feel free to discuss it here and I could determine if this authenticator can do what you're trying to achieve.

**Comment by keith6014** [comment]
I have active directory. I put in my username and password and I can authenticate because I am in the particular group. Instead of me putting in my username and password, it would be great to use REMOTE_USER and determine if I am in the LDAP group. I know I can do this Grafana.

**Comment by cwaldbieser** [comment]
It sounds like you have some way of authenticating the user already.  You just want to use the authenticated principal to determine whether the user is authorized to use this particular service.

The REMOTE_USER authenticator isn't going to be much help here.  It really assumes that all authentication and authorization have already happened.

My [jhub_cas_authenticator](https://github.com/cwaldbieser/jhub_cas_authenticator) shows how attributes provided during authentication can be used to enforce access control.

What you really want is a new kind of "authenticator" that doesn't do authentication-- just LDAP group-based authorization.  It could be modeled off of the base jhub.auth.Authenticator just like both of mine were.  You'd just accept the principal somehow-- maybe in a header just like in REMOTE_USER.  Then you'd need to make the actual LDAP queries to authorize the principal.

Obviously, making an LDAP query can require a bit more configuration (host, base DN, credentials, etc.) and the Jupyter configuration might also want to specify things like which group to inspect for authorization.  This query would need to be made asynchronously so the Hub wasn't blocked.

I hope that points you in the right direction.

**Comment by keith6014** [comment]
Thanks. I think its a bit over my head :-)
