### ISSUE TITLE
Upload to pypi

### ISSUE THREAD

**Issue by acordiner** [cwaldbieser/jhub_remote_user_authenticator#3]
It would be great to build a Python package and upload to the public Pypi repo, so that this can be installed easily with pip.

**Comment by cwaldbieser** [comment]
That sounds like a good idea.  I've never actually uploaded anything to PyPI, before, so I'll have to read up on it and see what's involved.  I'm thinking it shouldn't be too hard for a small project like this one.

**Comment by cwaldbieser** [comment]
This is the first time I released something on PYPI, so I'll apologize in advance if I made some bizarre configuration, but I *think* I've successfully pushed a distribution.  I was able to install it in a test virtualenv with `pip`.  It pulled down jupyterhub as a dependency.  If something doesn't seem correct, please feel free to re-open this issue or open a new issue.
