### ISSUE TITLE
Nginx drops HTTP headers with underscores

### ISSUE THREAD

**Issue by zcesur** [cwaldbieser/jhub_remote_user_authenticator#6]
From [Missing (disappearing) HTTP Headers](https://www.nginx.com/resources/wiki/start/topics/tutorials/config_pitfalls/#missing-disappearing-http-headers):
> If you do not explicitly set `underscores_in_headers on;`, NGINX will silently drop HTTP headers with underscores (which are perfectly valid according to the HTTP standard). This is done in order to prevent ambiguities when mapping headers to CGI variables as both dashes and underscores are mapped to underscores during that process.

Took me a while to figure out why my header was getting dropped haha! I suggest adding a warning or even changing the current header name so that others won't need to go through the same struggles.

**Comment by cwaldbieser** [comment]
I added a note in the `README.rst` in the master branch.  I linked to the NGINX docs for "underscores_in_headers".
I like NGINX, but consider this an odd choice, as it breaks an established standard.  E.g. apache won't silently drop your headers like this.
