### ISSUE TITLE
jhub_remote_user_authenticator

### ISSUE THREAD

**Issue by ankit2894** [cwaldbieser/jhub_remote_user_authenticator#8]
I am not able to setup remote_user authentication,Can u please share step by step process to do so!!!

**Comment by cwaldbieser** [comment]
Did you follow the instructions in the README?[1]  You install the `jhub_remote_user_authenticator` package into the same Python environment as your Jupyterhub.  Then you edit the Jupyterhub configuration and add or replace the setting:

  c.JupyterHub.authenticator_class = 'jhub_remote_user_authenticator.remote_user_auth.RemoteUserAuthenticator'

Then the next time you start Jupyterhub, it will populate the username from the REMOTE_USER header in the HTTP request.

You typically set this header with some kind of authenticating proxy and a web SSO system like [CAS](https://github.com/apereo/cas) or [Shibboleth](https://www.internet2.edu/products-services/trust-identity/shibboleth/).

What have you tried already?

[1] https://github.com/cwaldbieser/jhub_remote_user_authenticator/blob/master/README.rst

**Comment by ankit2894** [comment]
I followed the instructions but I am stuck with, how to set the REMOTE_USER header??

**Comment by cwaldbieser** [comment]
Let's start from the beginning-- what kind of authentication do you want to use?  CAS?  SAML2?  LDAP?  Something else?  The type of authentication you want to use influences how you set the REMOTE_USER header in the HTTP request.

**Comment by ankit2894** [comment]
I want to embed jupyterhub in my existing web application.I want the user logged into my application to login to jupyterhub directly without any further authentication.

**Comment by ankit2894** [comment]
This is why I wanted the remote user authentication.Please guide me with the process of implementation of the same..

**Comment by cwaldbieser** [comment]
Architecturally, Jupyterhub isn't embedded in your web application.  It looks more like an authenticating web proxy is placed in front of both your your application and Jupyterhub.  Authentication happens at the web proxy, and then it sets the REMOTE_USER header or environment variable which it sends to both your web application and to Jupyterhub.

E.g. if your web app is Java-based, you could have Apache httpd in front of it and use [mod_proxy_ajp](https://httpd.apache.org/docs/2.4/mod/mod_proxy_ajp.html) to talk to your servlet container.  Then you could use some kind of authentication module in Apache-- for example [mod_auth_form](https://httpd.apache.org/docs/2.4/mod/mod_auth_form.html).

You probably also need [mod_proxy_wstunnel](https://httpd.apache.org/docs/2.4/mod/mod_proxy_wstunnel.html) for proxying web sockets that Jupyterhub uses.

Your browser would connect to the web proxy (Apache httpd) and it would connect to both your web app and to Jupyterhub.

**Comment by ankit2894** [comment]
Is there any way out for me to use the same Login-ID and password for my app and jhub both?
Means can i provide some dummy password for all the registered usernames in the jhub's config file??

**Comment by cwaldbieser** [comment]
To be clear, that is something that this authenticator cannot do.
Now you are asking if there is some kind of "Same Sign-On" where the credentials for 2 or more applications are the same.  This is typically the case when multiple applications use the same password database, for example they both use the same LDAP directory or AD to authenticate.

You should probably ask on the [Project Jupyter Google Group](https://groups.google.com/forum/#!forum/jupyter) if you have questions about how to integrate Jupyter into your application.

**Comment by powerLeePlus** [comment]
@ankit2894 
Have you solved the problem？？
